on:
  push:
    branches:
      - "main"

permissions:
  contents: write
  pull-requests: write

name: Release Workflow

jobs:
  release-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Release with release-please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
